#!/usr/bin/env zsh

STOW_FOLDERS="zsh,bash,nvim,gitconfig,gh,starship,tmux"

DOT_FILES=$HOME/.dotfiles

pushd $DOT_FILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -D $folder
    stow $folder
done
popd
